package PD_1;

import classPackage.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Artjoms Sidorevics
 */


public class PD_1_Sidorevics extends javax.swing.JFrame {
    /**
     * Creates new form PD_1
     */
    public PD_1_Sidorevics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testOneBGroup = new javax.swing.ButtonGroup();
        jAdmin = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRegistration = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextLastName = new javax.swing.JTextField();
        jTextLogin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextPasswordRepeat = new javax.swing.JTextField();
        jLabelErr = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jQuizChoice = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTestOne = new javax.swing.JButton();
        jTestTwo = new javax.swing.JButton();
        jTestThree = new javax.swing.JButton();
        jTestFour = new javax.swing.JButton();
        jPicture1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMGS1Test = new javax.swing.JDialog();
        jMGS1Panel = new javax.swing.JPanel();
        jTestOneQuestionText = new javax.swing.JLabel();
        jTest1AnswerOne = new javax.swing.JRadioButton();
        jTest1AnswerTwo = new javax.swing.JRadioButton();
        jTest1AnswerThree = new javax.swing.JRadioButton();
        jTest1AnswerFour = new javax.swing.JRadioButton();
        jTestOneNextButton = new javax.swing.JButton();
        jMGS2Test = new javax.swing.JDialog();
        jMGS2Panel = new javax.swing.JPanel();
        jTestTwoQuestionText = new javax.swing.JLabel();
        jTest2AnswerOne = new javax.swing.JRadioButton();
        jTest2AnswerTwo = new javax.swing.JRadioButton();
        jTest2AnswerFour = new javax.swing.JRadioButton();
        jTestTwoNextButton = new javax.swing.JButton();
        jTest2AnswerThree = new javax.swing.JRadioButton();
        jHelpWindowLogin = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jHelpWindowRegist = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jHelpWindowQuiz = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jMGS3Test = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jTest3QuestionText = new javax.swing.JLabel();
        jTest3AnswerOne = new javax.swing.JRadioButton();
        jTest3AnswerTwo = new javax.swing.JRadioButton();
        jTest3AnswerThree = new javax.swing.JRadioButton();
        jTest3AnswerFour = new javax.swing.JRadioButton();
        jTestThreeNextButton = new javax.swing.JButton();
        jMGS4Test = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jTest4QuestionText = new javax.swing.JLabel();
        jTest4AnswerOne = new javax.swing.JRadioButton();
        jTest4AnswerTwo = new javax.swing.JRadioButton();
        jTest4AnswerThree = new javax.swing.JRadioButton();
        jTest4AnswerFour = new javax.swing.JRadioButton();
        jTestFourNextButton = new javax.swing.JButton();
        jResultDialog = new javax.swing.JDialog();
        jResultExitButton = new javax.swing.JButton();
        jTestResultLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLoginLoginField = new javax.swing.JTextField();
        jLoginPasswordField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSysSignal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setText("Admin's Place");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jAdminLayout = new javax.swing.GroupLayout(jAdmin.getContentPane());
        jAdmin.getContentPane().setLayout(jAdminLayout);
        jAdminLayout.setHorizontalGroup(
            jAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jAdminLayout.setVerticalGroup(
            jAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrēšanas forma");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Uzvards");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Vards");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Lietotājvārds");

        jButton4.setText("Atcelt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Pieslegties");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Parole");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Parole (atkartot)");

        jLabelErr.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setText("Help");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErr)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(116, 116, 116)
                                        .addComponent(jButton5))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextName)
                                    .addComponent(jTextLastName)
                                    .addComponent(jTextLogin)
                                    .addComponent(jTextPassword)
                                    .addComponent(jTextPasswordRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPasswordRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42)
                .addComponent(jLabelErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        javax.swing.GroupLayout jRegistrationLayout = new javax.swing.GroupLayout(jRegistration.getContentPane());
        jRegistration.getContentPane().setLayout(jRegistrationLayout);
        jRegistrationLayout.setHorizontalGroup(
            jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jRegistrationLayout.setVerticalGroup(
            jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setText("Izveleties jusu testu:");

        jTestOne.setText("Metal Gear Solid");
        jTestOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestOneActionPerformed(evt);
            }
        });

        jTestTwo.setText("Metal Gear Solid 2: Sons of Liberty");
        jTestTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestTwoActionPerformed(evt);
            }
        });

        jTestThree.setText("Metal Gear Solid 3: Snake Eater");
        jTestThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestThreeActionPerformed(evt);
            }
        });

        jTestFour.setText("Metal Gear Solid 4: Guns of the Patriots");
        jTestFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestFourActionPerformed(evt);
            }
        });

        jLabel14.setText("Help");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jButton6.setText("Return");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTestOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPicture1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTestTwo)
                                .addComponent(jTestThree)
                                .addComponent(jTestFour))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTestOne)
                    .addComponent(jPicture1))
                .addGap(18, 18, 18)
                .addComponent(jTestTwo)
                .addGap(18, 18, 18)
                .addComponent(jTestThree)
                .addGap(18, 18, 18)
                .addComponent(jTestFour)
                .addGap(38, 38, 38)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jQuizChoiceLayout = new javax.swing.GroupLayout(jQuizChoice.getContentPane());
        jQuizChoice.getContentPane().setLayout(jQuizChoiceLayout);
        jQuizChoiceLayout.setHorizontalGroup(
            jQuizChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jQuizChoiceLayout.setVerticalGroup(
            jQuizChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTestOneNextButton.setText("Next");
        jTestOneNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestOneNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMGS1PanelLayout = new javax.swing.GroupLayout(jMGS1Panel);
        jMGS1Panel.setLayout(jMGS1PanelLayout);
        jMGS1PanelLayout.setHorizontalGroup(
            jMGS1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMGS1PanelLayout.createSequentialGroup()
                .addGroup(jMGS1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMGS1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jMGS1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTest1AnswerOne)
                            .addComponent(jTest1AnswerTwo)
                            .addComponent(jTest1AnswerThree)
                            .addComponent(jTest1AnswerFour))
                        .addGap(0, 369, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMGS1PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTestOneNextButton)))
                .addContainerGap())
            .addComponent(jTestOneQuestionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMGS1PanelLayout.setVerticalGroup(
            jMGS1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMGS1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestOneQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jTest1AnswerOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTest1AnswerTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTest1AnswerThree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTest1AnswerFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jTestOneNextButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jMGS1TestLayout = new javax.swing.GroupLayout(jMGS1Test.getContentPane());
        jMGS1Test.getContentPane().setLayout(jMGS1TestLayout);
        jMGS1TestLayout.setHorizontalGroup(
            jMGS1TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMGS1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMGS1TestLayout.setVerticalGroup(
            jMGS1TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMGS1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTestTwoNextButton.setText("Next");
        jTestTwoNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestTwoNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMGS2PanelLayout = new javax.swing.GroupLayout(jMGS2Panel);
        jMGS2Panel.setLayout(jMGS2PanelLayout);
        jMGS2PanelLayout.setHorizontalGroup(
            jMGS2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMGS2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMGS2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTestTwoQuestionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMGS2PanelLayout.createSequentialGroup()
                        .addGap(0, 312, Short.MAX_VALUE)
                        .addComponent(jTestTwoNextButton))
                    .addGroup(jMGS2PanelLayout.createSequentialGroup()
                        .addGroup(jMGS2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTest2AnswerOne)
                            .addComponent(jTest2AnswerTwo)
                            .addComponent(jTest2AnswerFour)
                            .addComponent(jTest2AnswerThree))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jMGS2PanelLayout.setVerticalGroup(
            jMGS2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMGS2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestTwoQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jTest2AnswerOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest2AnswerTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest2AnswerThree)
                .addGap(11, 11, 11)
                .addComponent(jTest2AnswerFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jTestTwoNextButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jMGS2TestLayout = new javax.swing.GroupLayout(jMGS2Test.getContentPane());
        jMGS2Test.getContentPane().setLayout(jMGS2TestLayout);
        jMGS2TestLayout.setHorizontalGroup(
            jMGS2TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMGS2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMGS2TestLayout.setVerticalGroup(
            jMGS2TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMGS2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("If you have problems with login, thy these:\n1.) Check is your login are correct\n2.) Check is your password is correct\n\nIf you new, try registration, to create new login and password");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jHelpWindowLoginLayout = new javax.swing.GroupLayout(jHelpWindowLogin.getContentPane());
        jHelpWindowLogin.getContentPane().setLayout(jHelpWindowLoginLayout);
        jHelpWindowLoginLayout.setHorizontalGroup(
            jHelpWindowLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHelpWindowLoginLayout.setVerticalGroup(
            jHelpWindowLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Fill all lines with your data\n\nIf your passwords didn't match, programm will show you that they \ndon't match");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jHelpWindowRegistLayout = new javax.swing.GroupLayout(jHelpWindowRegist.getContentPane());
        jHelpWindowRegist.getContentPane().setLayout(jHelpWindowRegistLayout);
        jHelpWindowRegistLayout.setHorizontalGroup(
            jHelpWindowRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHelpWindowRegistLayout.setVerticalGroup(
            jHelpWindowRegistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Click the button with test name and thest will start\n\nWhen you answer all questions, button will switch from \"Next\" to \"End\"\nwhen you click \"End\" button, test will close and your correct answers \nwill be written to database\n");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jHelpWindowQuizLayout = new javax.swing.GroupLayout(jHelpWindowQuiz.getContentPane());
        jHelpWindowQuiz.getContentPane().setLayout(jHelpWindowQuizLayout);
        jHelpWindowQuizLayout.setHorizontalGroup(
            jHelpWindowQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jHelpWindowQuizLayout.setVerticalGroup(
            jHelpWindowQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTestThreeNextButton.setText("Next");
        jTestThreeNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestThreeNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTest3QuestionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTest3AnswerOne)
                            .addComponent(jTest3AnswerTwo)
                            .addComponent(jTest3AnswerThree)
                            .addComponent(jTest3AnswerFour))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(jTestThreeNextButton)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTest3QuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jTest3AnswerOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest3AnswerTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest3AnswerThree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest3AnswerFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jTestThreeNextButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jMGS3TestLayout = new javax.swing.GroupLayout(jMGS3Test.getContentPane());
        jMGS3Test.getContentPane().setLayout(jMGS3TestLayout);
        jMGS3TestLayout.setHorizontalGroup(
            jMGS3TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMGS3TestLayout.setVerticalGroup(
            jMGS3TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTest4AnswerOne.setText("jRadioButton1");

        jTest4AnswerTwo.setText("jRadioButton2");

        jTest4AnswerThree.setText("jRadioButton3");

        jTest4AnswerFour.setText("jRadioButton4");

        jTestFourNextButton.setText("Next");
        jTestFourNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestFourNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTest4QuestionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTest4AnswerOne)
                            .addComponent(jTest4AnswerTwo)
                            .addComponent(jTest4AnswerThree)
                            .addComponent(jTest4AnswerFour))
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTestFourNextButton)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTest4QuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jTest4AnswerOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest4AnswerTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest4AnswerThree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTest4AnswerFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jTestFourNextButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jMGS4TestLayout = new javax.swing.GroupLayout(jMGS4Test.getContentPane());
        jMGS4Test.getContentPane().setLayout(jMGS4TestLayout);
        jMGS4TestLayout.setHorizontalGroup(
            jMGS4TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMGS4TestLayout.setVerticalGroup(
            jMGS4TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jResultExitButton.setText("Exit");
        jResultExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResultExitButtonActionPerformed(evt);
            }
        });

        jTestResultLabel.setText("jLabel16");

        javax.swing.GroupLayout jResultDialogLayout = new javax.swing.GroupLayout(jResultDialog.getContentPane());
        jResultDialog.getContentPane().setLayout(jResultDialogLayout);
        jResultDialogLayout.setHorizontalGroup(
            jResultDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultDialogLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jResultExitButton)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(jResultDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jResultDialogLayout.setVerticalGroup(
            jResultDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultDialogLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jTestResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jResultExitButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setBackground(new java.awt.Color(79, 129, 189));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLoginLoginField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 93, 138), 3, true));

        jLoginPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 93, 138), 3, true));

        jLabel2.setBackground(new java.awt.Color(192, 80, 77));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel2.setText("Login");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jButton1.setBackground(new java.awt.Color(190, 75, 75));
        jButton1.setText("Exit");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(74, 126, 187));
        jButton2.setText("Login");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Noklikšķiniet šeit, lai izveidotu kontu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setText("Palidzība");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLoginLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSysSignal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLoginLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jSysSignal)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jRegistration.setBounds(400,300, 495, 470);
        jRegistration.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String login = jLoginLoginField.getText();
        String password = jLoginPasswordField.getText();
        FileOutClass out = new FileOutClass();
        for(User u: User.userDB){
            if(u.enter(login, password)){
                User.currentUser = u;
                jLabel15.setText(login);
                jQuizChoice.setVisible(true);
                jQuizChoice.setBounds(400,300, 495, 470);
            }
            else{
                jSysSignal.setText("Wrong Login or Password");
            }
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = jTextName.getText();
        String login = jTextLogin.getText();
        String password = jTextPassword.getText();
        String password_repeat = jTextPasswordRepeat.getText();
        FileInputClass file = new FileInputClass(name, login, password, password_repeat, jLabelErr);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jRegistration.setVisible(false);
        jTextName.setText("");
        jTextLogin.setText("");
        jTextPassword.setText("");
        jTextLastName.setText("");
        jTextPasswordRepeat.setText("");  
        jLabelErr.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTestOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestOneActionPerformed
        jMGS1Test.setVisible(true);
        jMGS1Test.setBounds(400,300, 495, 470);        
        QuestionFileOut test = new QuestionFileOut("MGS1QuestionDB.txt");
        testOneBGroup.add(jTest1AnswerOne);
        testOneBGroup.add(jTest1AnswerTwo);
        testOneBGroup.add(jTest1AnswerThree);
        testOneBGroup.add(jTest1AnswerFour);
        for(Question q: Question.questions){
            Question.currentQuestion = q;
            q.setQuestionText(jTestOneQuestionText);
            q.setAnswers(jTest1AnswerOne, 0);
            q.setAnswers(jTest1AnswerTwo, 1);
            q.setAnswers(jTest1AnswerThree, 2);
            q.setAnswers(jTest1AnswerFour, 3);
            q.getCorrctAnswer();
        }    
    }//GEN-LAST:event_jTestOneActionPerformed

    private void jTestOneNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestOneNextButtonActionPerformed
       int answerTestOne = 0;
       
       if (!(jTest1AnswerOne.isSelected() ||
           jTest1AnswerTwo.isSelected() ||
           jTest1AnswerThree.isSelected() ||
           jTest1AnswerFour.isSelected()))
       {
           return;
       }
       
        if (jTest1AnswerOne.isSelected()) {
            answerTestOne = 1;
            Question.currentQuestionID++;
        } 
        else if (jTest1AnswerTwo.isSelected()) {
            answerTestOne = 2;
            Question.currentQuestionID++;
        } 
        else if (jTest1AnswerThree.isSelected()) {
            answerTestOne = 3;
            Question.currentQuestionID++;
        } 
        else if (jTest1AnswerFour.isSelected()) {
            answerTestOne = 4;
            Question.currentQuestionID++;
        }
        if (Question.currentQuestion.isCorrectAnswer(answerTestOne)) {
            User.currentUser.plusRightAnswer();
        }
        if (Question.currentQuestionID <= Question.questions.size()-2) {
            Question q = Question.questions.get(Question.currentQuestionID);
            Question.currentQuestion = q;
            q.setQuestionText(jTestOneQuestionText);
            q.setAnswers(jTest1AnswerOne, 0);
            q.setAnswers(jTest1AnswerTwo, 1);
            q.setAnswers(jTest1AnswerThree, 2);
            q.setAnswers(jTest1AnswerFour, 3);
            testOneBGroup.clearSelection();
            if (Question.currentQuestionID == Question.questions.size()-2) {
                jTestOneNextButton.setText("End");
            }
        } 
        else {
            jMGS1Test.setVisible(false);
            jResultDialog.setBounds(400,300, 495, 470);
            jResultDialog.setVisible(true);
            jTestResultLabel.setText(User.currentUser.getName()+" Your result is: "+User.currentUser.getMark());
            FileInputClass mark = new FileInputClass(User.currentUser, "MGS1 Test");
            Question.currentQuestionID=0;
            User.currentUser.setMarkNull();
        }
    }//GEN-LAST:event_jTestOneNextButtonActionPerformed

    private void jTestTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestTwoActionPerformed
        jMGS2Test.setVisible(true);
        jMGS2Test.setBounds(400,300, 495, 470);        
        QuestionFileOut test = new QuestionFileOut("MGS2QuestionDB.txt");
        testOneBGroup.add(jTest2AnswerOne);
        testOneBGroup.add(jTest2AnswerTwo);
        testOneBGroup.add(jTest2AnswerThree);
        testOneBGroup.add(jTest2AnswerFour);
        for(Question q: Question.questions){
            Question.currentQuestion = q;
            q.setQuestionText(jTestTwoQuestionText);
            q.setAnswers(jTest2AnswerOne, 0);
            q.setAnswers(jTest2AnswerTwo, 1);
            q.setAnswers(jTest2AnswerThree, 2);
            q.setAnswers(jTest2AnswerFour, 3);
            q.getCorrctAnswer();            
        }
    }//GEN-LAST:event_jTestTwoActionPerformed

    private void jTestTwoNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestTwoNextButtonActionPerformed
       int answerTestTwo = 0;
        if (!(jTest2AnswerOne.isSelected() ||
           jTest2AnswerTwo.isSelected() ||
           jTest2AnswerThree.isSelected() ||
           jTest2AnswerFour.isSelected()))
       {
           return;
       }
        if (jTest2AnswerOne.isSelected()) {
            answerTestTwo = 1;
            Question.currentQuestionID++;
        } 
        else if (jTest2AnswerTwo.isSelected()) {
            answerTestTwo = 2;
            Question.currentQuestionID++;
        } 
        else if (jTest2AnswerThree.isSelected()) {
            answerTestTwo = 3;
            Question.currentQuestionID++;
        } 
        else if (jTest2AnswerFour.isSelected()) {
            answerTestTwo = 4;
            Question.currentQuestionID++;
        }
        if (Question.currentQuestion.isCorrectAnswer(answerTestTwo)) {
            User.currentUser.plusRightAnswer();
        }
        if (Question.currentQuestionID <= Question.questions.size()-1) {
            Question q = Question.questions.get(Question.currentQuestionID - 1);
            Question.currentQuestion = q;
            q.setQuestionText(jTestTwoQuestionText);
            q.setAnswers(jTest2AnswerOne, 0);
            q.setAnswers(jTest2AnswerTwo, 1);
            q.setAnswers(jTest2AnswerThree, 2);
            q.setAnswers(jTest2AnswerFour, 3);
            testOneBGroup.clearSelection();
            if (Question.currentQuestionID == Question.questions.size()-1) {
                jTestTwoNextButton.setText("End");
            }
        } 
        else {
            jMGS2Test.setVisible(false);
            jResultDialog.setBounds(400,300, 495, 470);
            jResultDialog.setVisible(true);
            jTestResultLabel.setText(User.currentUser.getName()+" Your result is: "+User.currentUser.getMark());
            FileInputClass mark = new FileInputClass(User.currentUser, "MGS2 Test");
            Question.currentQuestionID=0;
            User.currentUser.setMarkNull();
        }
    }//GEN-LAST:event_jTestTwoNextButtonActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        jHelpWindowLogin.setBounds(400,300, 495, 470);
        jHelpWindowLogin.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        jHelpWindowRegist.setBounds(400,300, 495, 470);
        jHelpWindowRegist.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        jHelpWindowQuiz.setBounds(400,300, 495, 470);
        jHelpWindowQuiz.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jQuizChoice.setVisible(false);
        jLoginLoginField.setText("");
        jLoginPasswordField.setText("");
        User.currentUser = null;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTestThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestThreeActionPerformed
        jMGS3Test.setVisible(true);
        jMGS3Test.setBounds(400,300, 495, 470);        
        QuestionFileOut test = new QuestionFileOut("MGS3QuestionDB.txt");
        testOneBGroup.add(jTest3AnswerOne);
        testOneBGroup.add(jTest3AnswerTwo);
        testOneBGroup.add(jTest3AnswerThree);
        testOneBGroup.add(jTest3AnswerFour);
        for(Question q: Question.questions){
            Question.currentQuestion = q;
            q.setQuestionText(jTest3QuestionText);
            q.setAnswers(jTest3AnswerOne, 0);
            q.setAnswers(jTest3AnswerTwo, 1);
            q.setAnswers(jTest3AnswerThree, 2);
            q.setAnswers(jTest3AnswerFour, 3);
            q.getCorrctAnswer();
        }
    }//GEN-LAST:event_jTestThreeActionPerformed

    private void jTestThreeNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestThreeNextButtonActionPerformed
        int answerTestTwo = 0;
        if (!(jTest3AnswerOne.isSelected() ||
           jTest3AnswerTwo.isSelected() ||
           jTest3AnswerThree.isSelected() ||
           jTest3AnswerFour.isSelected()))
        {
           return;
        }
        if (jTest3AnswerOne.isSelected()) {
            answerTestTwo = 1;
            Question.currentQuestionID++;
        } 
        else if (jTest3AnswerTwo.isSelected()) {
            answerTestTwo = 2;
            Question.currentQuestionID++;
        } 
        else if (jTest3AnswerThree.isSelected()) {
            answerTestTwo = 3;
            Question.currentQuestionID++;
        } 
        else if (jTest3AnswerFour.isSelected()) {
            answerTestTwo = 4;
            Question.currentQuestionID++;
        }
        if (Question.currentQuestion.isCorrectAnswer(answerTestTwo)) {
            User.currentUser.plusRightAnswer();
        }
        if (Question.currentQuestionID <= Question.questions.size()-1) {
            Question q = Question.questions.get(Question.currentQuestionID - 1);
            Question.currentQuestion = q;
            q.setQuestionText(jTest3QuestionText);
            q.setAnswers(jTest3AnswerOne, 0);
            q.setAnswers(jTest3AnswerTwo, 1);
            q.setAnswers(jTest3AnswerThree, 2);
            q.setAnswers(jTest3AnswerFour, 3);
            testOneBGroup.clearSelection();
            if (Question.currentQuestionID == Question.questions.size()-1) {
                jTestThreeNextButton.setText("End");
            }
        } 
        else {
            jMGS3Test.setVisible(false);
            jResultDialog.setBounds(400,300, 495, 470);
            jResultDialog.setVisible(true);
            jTestResultLabel.setText(User.currentUser.getName()+" Your result is: "+User.currentUser.getMark());
            FileInputClass mark = new FileInputClass(User.currentUser, "MGS3 Test");
            Question.currentQuestionID=0;
            User.currentUser.setMarkNull();
        }
    }//GEN-LAST:event_jTestThreeNextButtonActionPerformed

    private void jTestFourNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestFourNextButtonActionPerformed
       int answerTestTwo = 0;
        if (!(jTest4AnswerOne.isSelected() ||
           jTest4AnswerTwo.isSelected() ||
           jTest4AnswerThree.isSelected() ||
           jTest4AnswerFour.isSelected()))
        {
           return;
        }
        if (jTest4AnswerOne.isSelected()) {
            answerTestTwo = 1;
            Question.currentQuestionID++;
        } 
        else if (jTest4AnswerTwo.isSelected()) {
            answerTestTwo = 2;
            Question.currentQuestionID++;
        } 
        else if (jTest4AnswerThree.isSelected()) {
            answerTestTwo = 3;
            Question.currentQuestionID++;
        } 
        else if (jTest4AnswerFour.isSelected()) {
            answerTestTwo = 4;
            Question.currentQuestionID++;
        }
        if (Question.currentQuestion.isCorrectAnswer(answerTestTwo)) {
            User.currentUser.plusRightAnswer();
        }
        if (Question.currentQuestionID <= Question.questions.size()-1) {
            Question q = Question.questions.get(Question.currentQuestionID - 1);
            Question.currentQuestion = q;
            q.setQuestionText(jTest4QuestionText);
            q.setAnswers(jTest4AnswerOne, 0);
            q.setAnswers(jTest4AnswerTwo, 1);
            q.setAnswers(jTest4AnswerThree, 2);
            q.setAnswers(jTest4AnswerFour, 3);
            testOneBGroup.clearSelection();
            if (Question.currentQuestionID == Question.questions.size()-1) {
                jTestFourNextButton.setText("End");
            }
        } 
        else {
            jMGS4Test.setVisible(false);
            jResultDialog.setBounds(400,300, 495, 470);
            jResultDialog.setVisible(true);
            jTestResultLabel.setText(User.currentUser.getName()+" Your result is: "+User.currentUser.getMark());
            FileInputClass mark = new FileInputClass(User.currentUser, "MGS4 Test");
            Question.currentQuestionID=0;
            User.currentUser.setMarkNull();
        }
    }//GEN-LAST:event_jTestFourNextButtonActionPerformed

    private void jTestFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestFourActionPerformed
        jMGS4Test.setVisible(true);
        jMGS4Test.setBounds(400,300, 495, 470);        
        QuestionFileOut test = new QuestionFileOut("MGS4QuestionDB.txt");
        testOneBGroup.add(jTest4AnswerOne);
        testOneBGroup.add(jTest4AnswerTwo);
        testOneBGroup.add(jTest4AnswerThree);
        testOneBGroup.add(jTest4AnswerFour);
        for(Question q: Question.questions){
            Question.currentQuestion = q;
            q.setQuestionText(jTest4QuestionText);
            q.setAnswers(jTest4AnswerOne, 0);
            q.setAnswers(jTest4AnswerTwo, 1);
            q.setAnswers(jTest4AnswerThree, 2);
            q.setAnswers(jTest4AnswerFour, 3);
            q.getCorrctAnswer();
        }
    }//GEN-LAST:event_jTestFourActionPerformed

    private void jResultExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResultExitButtonActionPerformed
            jResultDialog.setVisible(false);
    }//GEN-LAST:event_jResultExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PD_1_Sidorevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PD_1_Sidorevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PD_1_Sidorevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PD_1_Sidorevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PD_1_Sidorevics().setBounds(400,300,495,470);
                new PD_1_Sidorevics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jHelpWindowLogin;
    private javax.swing.JDialog jHelpWindowQuiz;
    private javax.swing.JDialog jHelpWindowRegist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErr;
    private javax.swing.JTextField jLoginLoginField;
    private javax.swing.JTextField jLoginPasswordField;
    private javax.swing.JPanel jMGS1Panel;
    private javax.swing.JDialog jMGS1Test;
    private javax.swing.JPanel jMGS2Panel;
    private javax.swing.JDialog jMGS2Test;
    private javax.swing.JDialog jMGS3Test;
    private javax.swing.JDialog jMGS4Test;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jPicture1;
    private javax.swing.JDialog jQuizChoice;
    private javax.swing.JDialog jRegistration;
    private javax.swing.JDialog jResultDialog;
    private javax.swing.JButton jResultExitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jSysSignal;
    private javax.swing.JRadioButton jTest1AnswerFour;
    private javax.swing.JRadioButton jTest1AnswerOne;
    private javax.swing.JRadioButton jTest1AnswerThree;
    private javax.swing.JRadioButton jTest1AnswerTwo;
    private javax.swing.JRadioButton jTest2AnswerFour;
    private javax.swing.JRadioButton jTest2AnswerOne;
    private javax.swing.JRadioButton jTest2AnswerThree;
    private javax.swing.JRadioButton jTest2AnswerTwo;
    private javax.swing.JRadioButton jTest3AnswerFour;
    private javax.swing.JRadioButton jTest3AnswerOne;
    private javax.swing.JRadioButton jTest3AnswerThree;
    private javax.swing.JRadioButton jTest3AnswerTwo;
    private javax.swing.JLabel jTest3QuestionText;
    private javax.swing.JRadioButton jTest4AnswerFour;
    private javax.swing.JRadioButton jTest4AnswerOne;
    private javax.swing.JRadioButton jTest4AnswerThree;
    private javax.swing.JRadioButton jTest4AnswerTwo;
    private javax.swing.JLabel jTest4QuestionText;
    private javax.swing.JButton jTestFour;
    private javax.swing.JButton jTestFourNextButton;
    private javax.swing.JButton jTestOne;
    private javax.swing.JButton jTestOneNextButton;
    private javax.swing.JLabel jTestOneQuestionText;
    private javax.swing.JLabel jTestResultLabel;
    private javax.swing.JButton jTestThree;
    private javax.swing.JButton jTestThreeNextButton;
    private javax.swing.JButton jTestTwo;
    private javax.swing.JButton jTestTwoNextButton;
    private javax.swing.JLabel jTestTwoQuestionText;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextPasswordRepeat;
    private javax.swing.ButtonGroup testOneBGroup;
    // End of variables declaration//GEN-END:variables
}
